In [2]:
1.
import numpy as np
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
2.
import numpy as np
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
3.
import numpy as np
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[ 7  8  3  8  3]
 [ 5 10  3  7  4]
 [ 7  2  8  2  4]
 [10  8  4  4 10]
 [10  1  5  4  6]]


In [22]:
4.
import numpy as np
matrix = np.random.rand(4, 4)
print(matrix)

[[0.41008837 0.64542366 0.0675098  0.40911646]
 [0.25975416 0.38518052 0.55466906 0.71396515]
 [0.35030379 0.24617774 0.09047217 0.14537891]
 [0.7936356  0.81090223 0.3287067  0.20334409]]


In [27]:
5.
import numpy as np
a = np.random.randint(1, 10, size=(5))
b = np.random.randint(1, 10, size=(5))

sum_result = a+b
print(sum_result)

subtract_result = a-b
print(subtract_result)

multiply_result = a*b
print(multiply_result)

[11 15  5  7  3]
[-5 -3  3  3  1]
[24 54  4 10  2]


In [35]:
6.
import numpy as np
a = np.random.rand(7)
b = np.random.rand(7)

print(a*b)

[0.00184543 0.44386579 0.02775496 0.1777126  0.03498018 0.1019292
 0.14425035]


In [49]:
7.
import numpy as np
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

result = np.dot(matrix1, matrix2)
print(result)

[[ 58  40  38]
 [134 100  84]]


In [48]:
8.
import numpy as np
matrix = np.random.randint(1, 10, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)

[[-1.07142857  0.35714286  0.92857143]
 [ 1.75       -0.75       -1.25      ]
 [-0.03571429  0.17857143 -0.03571429]]


In [51]:
9.
import numpy as np
matrix = np.random.rand(4, 4)
transposed_matrix = matrix.T

print(transposed_matrix)

[[0.36948721 0.25583979 0.04241755 0.03593211]
 [0.97099134 0.21097062 0.66579606 0.93878466]
 [0.78917391 0.5005733  0.54471743 0.08196596]
 [0.44918383 0.45099745 0.88671137 0.27947837]]


In [87]:
10.
import numpy as np
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4))

result = np.dot(matrix, vector)
print(result)

[108 100 135]


In [90]:
11.
import numpy as np
matrix = np.random.rand(2, 3)
vector = np.random.rand (3)
multiply_result = np.multiply(matrix, vector)
print(multiply_result)

[[0.02322441 0.17907922 0.1779608 ]
 [0.00753847 0.61940305 0.16529357]]


In [86]:
12.
import numpy as np
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

multiply_result = np.multiply(matrix1, matrix2)
print(multiply_result)

[[50 40]
 [20  4]]


In [85]:
13.
import numpy as np
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

result = np.dot(matrix1, matrix2)
print(result)

[[109 110]
 [ 56  62]]


In [66]:
14.
import numpy as np
matrix = np.random.randint(1, 100, size=(5, 5))

sum_result = np.sum(matrix)
print(sum_result)

1096


In [68]:
15.
import numpy as np
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

subtraction_result = matrix1 - matrix2
print(subtraction_result)

[[ 3  1  3  5]
 [ 2 -2 -3  0]
 [ 4  1  4  9]
 [ 6  6  3  2]]


In [70]:
16.
import numpy as np
matrix = np.random.rand(3, 3)
sums_per_row = np.sum(matrix, axis=1, keepdims=True)

print(sums_per_row)

[[1.51529773]
 [0.46769135]
 [1.3630164 ]]


In [81]:
17.
import numpy as np
matrix = np.random.randint(1, 100, size=(3, 4))
matrix_squared = np.square(matrix)
print(matrix_squared)

[[3600 4900 1296 3025]
 [6561 3721 4489 1600]
 [1225 2304 9216 2809]]


In [84]:
18.
import numpy as np
vector = np.random.randint(1, 51, size=(4))
print(vector)

vector_squared = np.square(vector)
print(vector_squared)

[24 26 22 24]
[576 676 484 576]
